---------------------
#### Implement Grid World
-----------------------

In [1]:
import numpy as np

grid = np.zeros((5,5))
grid

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [2]:
nrows = 5
ncols = 5

In [3]:
grid = np.zeros((nrows, ncols))
grid

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
gamma = 0.9

In [5]:
# number of times we will go through the whole grid
n_iters = 1

In [20]:
for num in range(n_iters): 
    
    for i in range(nrows):        #all the rows
        for j in range(ncols):    #all the columns
      
            # if going up takes us out of the grid then its value be 0
            up_grid = grid[i-1][j] if i > 0 else 0   
            
            # if going down takes us out of the grid then its value be 0
            down_grid = grid[i+1][j] if i < 4 else 0  
            
            # if going left takes us out of the grid then its value be 0
            left_grid = grid[i][j-1] if j > 0 else 0  
            
            # if going right takes us out of the grid then its value be 0
            right_grid = grid[i][j+1] if j < 4 else 0  

            all_dirs = [up_grid, down_grid, left_grid, right_grid]     

            value = 0  
            
            if   i==0 and j==1:                   # the position of A
                value = 10 + gamma * grid[4][1]
            elif i==0 and j==3:                   # the position of B
                value =  5 + gamma * grid[2][3]
            else:
                for direc in all_dirs:
                    if direc != 0: 
                        value += .25 * ( 0 + gamma * direc)       # if we don't go out of the grid
                    else:
                        value += .25 * (-1 + gamma * grid[i][j])  # if we go out of the grid
        
            grid[i][j] = value

            print(i, j, grid)

0 0 [[-1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
0 1 [[-1. 10.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
0 2 [[-1.  10.   1.5  0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]]
0 3 [[-1.  10.   1.5  5.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]]
0 4 [[-1.    10.     1.5    5.     0.375]
 [ 0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.   ]]
1 0 [[-1.    10.     1.5    5.     0.375]
 [-0.975  0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.   ]]
1 1 [[-1.       10.        1.5       5.        0.375   ]
 [-0.975     1.530625  

In [21]:
np.round(grid, 1)

array([[-1. , 10. ,  1.5,  5. ,  0.4],
       [-1. ,  1.5,  0.2,  0.7, -0.3],
       [-1. , -0.4, -0.5, -0.5, -0.7],
       [-1. , -0.8, -0.8, -0.8, -0.8],
       [-1. , -0.9, -0.9, -0.9, -0.9]])